name: Continuos integration

on:
  push:  
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Usar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Remover node_modules e package-lock.json
        run: rm -rf node_modules package-lock.json

      - name: Limpar cache do npm
        run: npm cache clean --force

      - name: Instalar dependências com npm ci
        run: npm ci

      - name: Build do projeto
        run: npm run build --if-present

      - name: Rodar testes (placeholder)
        run: npm test
